spring:
  application:
    name: Planner_BE

  datasource:
    url: jdbc:mysql://localhost:3306/planner?serverTimezone=Asia/Seoul
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}

kcisa:
  base-url: https://api.kcisa.kr/openapi/API_CNV_063/request
  service-key: ${KCISA_SERVICE_KEY}